markdown: rdiscount
plugins: ./_plugins
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true


title : K
author :
  name : 程琨
  email : aegean.ck@gmail.com
  github : xiaokchengkun
  sina : 小K_傲娇空
  gravatar: c375994dd0027ce6f0d4948ba7ace4a3

nav :
  - text: 首页
    url: /pages.html
    icon: icon-home
    class: home
#  - text: 日志
#    url: /index.html
#    icon: icon-book
#    class: none
  - text: 文章归档
    url: /archive.html
    icon: icon-reorder
    class: none
  - text: 关于我
    url: /about.html
    icon: icon-envelope-alt
    class: none
  - text: 联系我
    url: /contact.html
    icon: icon-heart
    class: none
  - text: github
    url: https://github.com/xiaokchengkun
    icon: icon-github
    class: none


production_url : http://xiaokchengkun.github.io

JB :
  version : 0.3.0

  BASE_PATH : false
  ASSET_PATH : false

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml


  comments :
    provider : disqus
    disqus :
      short_name : jekyllbootstrap

  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-123-12'

  sharing :
    provider : false


